name = "malasuertelandv"
author = "soldeeex"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf71b5340e3088cab3219433529a40c3f984cabdf8324df1b13d2ffb24f1c6b3"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
