name = "Mala Suerteland V"
author = "soldeeex"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feeee9f61c037504e8bc070761108bb94ec4310567214cc2bb37738c6ecfd312"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
