name = "Mala Suerteland V"
author = "soldeeex"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dcda7669d71105d7a1e6a4fba1e0c269c151a037780370f5d0a236b7a0e756b"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
