name = "Mala Suerteland V"
author = "soldeeex"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c02944cd80f583e555157c1f3bf3e2a3c576f09c313ef9749e49d8ebb260e9d"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
