name = "Mala Suerteland V"
author = "soldeeex"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf3cefda3a8df61072af84498da74e40207ec4377d45970728fab4c387ac2cc7"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
