name = "malasuertelandv"
author = "soldeeex"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06b4fcee6458b42a92c92bf1c0e06784f9a701596296ff3fde09343862e62d46"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
