name = "Mala Suerteland V"
author = "soldeeex"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b8d106e22a585bc243be298b1c29499754ea559101098af6db5ea332f496f85"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
