name = "malasuertelandv"
author = "soldeeex"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ca896712924242fefe9c2d797ef8a2bdb91d92ef7649af4abe498c4528302bb"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
