# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "fancy"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "fancy"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				panda = true
				axolotl = true
				bee = true
				arrow = true
				donkey = true
				cow = true
				fox = true
				chest_minecart = true
				tropical_fish = true
				pig = true
				slime = true
				pillager = true
				skeleton = true
				iron_golem = true
				bat = true
				cat = true
				rabbit = true
				zombie = true
				silverfish = true
				drowned = true
				sheep = true
				experience_orb = true
				player = true
				dolphin = true
				item = true
				turtle = true
				villager = true
				wolf = true
				salmon = true
				tnt_minecart = true
				zombie_villager = true
				horse = true
				phantom = true
				witch = true
				glow_squid = true
				cod = true
				glow_item_frame = false
				squid = true
				spider = true
				parrot = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.betteranimalsplus]
				deer = true
				feralwolf = true
				jellyfish = true
				goose = true
				songbird = true
				badgerdirt = true
				eel_freshwater = true
				boar = true
				dragonfly = true
				whale = true
				lamprey = true
				butterfly = true
				pheasant = true
				blackbear = true
				shark = true
				piranha = true
				bobbit_worm = true
				nautilus = true
				moose = true
				tarantula = true
				badger = true
				eel_saltwater = true
				squirrel = true
				brownbear = true
				turkey = true
				coyote = true
				lammergeier = true
				crab = true

			[light_sources.settings.entities.earthtojavamobs]
				moolip = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				coconut_crab = true

			[light_sources.settings.entities.creeperoverhaul]
				cave_creeper = true

			[light_sources.settings.entities.megaparrot]
				megaparrot = true

			[light_sources.settings.entities.tinyskeletons]
				baby_skeleton = true

